name: Deploy to Apache2 Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Release Directory
        run: echo "RELEASE_DIR=${{ vars.DEPLOY_PATH }}/releases/$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Deploy to Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "."
          target: "${{ env.RELEASE_DIR }}"

      - name: Restart Apache and Update Symlink
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            ln -sfn ${{ env.RELEASE_DIR }} ${{ vars.DEPLOY_PATH }}/current
            sudo systemctl restart apache2
