name: Deploy to Apache2

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Disable sudo password prompt
        run: |
          echo "sysadmin ALL=(ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/90-cloud-init-users

      - name: Deploy to server
        run: |
          ssh -t -p 44 -o StrictHostKeyChecking=no sysadmin@69.54.142.142 << 'EOF'
            cd /var/www/html/
            # Use the personal access token for authentication
            git pull https://username:${{ secrets.GH_TOKEN }}@github.com/cartersexton/c_squared.git main
            sudo systemctl restart apache2
          EOF
